# Generated by Django 3.1.4 on 2021-01-22 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('Casual Shoes', 'Casual Shoe'), ('Formal Shoes', 'Formal Shoe'), ('Sports Shoes', 'Sport Shoe')], max_length=20),
        ),
    ]
