# Generated by Django 3.1.4 on 2021-01-22 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('Adidas', 'Adidas'), ('Bata', 'Bata'), ('Metro', 'Metro'), ('Nike', 'Nike'), ('Reebok', 'Reebok')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[(" 'Men's Wear' ", " 'Men's Wear' "), (" 'Women's Wear' ", " 'Women's Wear' "), (" 'Kid's Wear' ", " 'Kid's Wear' ")], max_length=20),
        ),
    ]
